// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMu544lu7GYByTBEHaeBe8Ld5YlaGc54',
    appId: '1:243357669534:web:6061ec95d866392ae8c38f',
    messagingSenderId: '243357669534',
    projectId: 'vivalink-5b6a0',
    authDomain: 'vivalink-5b6a0.firebaseapp.com',
    databaseURL: 'https://vivalink-5b6a0-default-rtdb.firebaseio.com',
    storageBucket: 'vivalink-5b6a0.firebasestorage.app',
    measurementId: 'G-LSVJ22TLH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ23aAeaO4jcQjUgKvJJs1JaZLmAOxB9M',
    appId: '1:243357669534:android:25d29f19ed413a67e8c38f',
    messagingSenderId: '243357669534',
    projectId: 'vivalink-5b6a0',
    databaseURL: 'https://vivalink-5b6a0-default-rtdb.firebaseio.com',
    storageBucket: 'vivalink-5b6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFz5bWymWgmwHmVY7LksgNHqJYXi7f80',
    appId: '1:243357669534:ios:5ae57e1e71beabece8c38f',
    messagingSenderId: '243357669534',
    projectId: 'vivalink-5b6a0',
    databaseURL: 'https://vivalink-5b6a0-default-rtdb.firebaseio.com',
    storageBucket: 'vivalink-5b6a0.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFz5bWymWgmwHmVY7LksgNHqJYXi7f80',
    appId: '1:243357669534:ios:5ae57e1e71beabece8c38f',
    messagingSenderId: '243357669534',
    projectId: 'vivalink-5b6a0',
    databaseURL: 'https://vivalink-5b6a0-default-rtdb.firebaseio.com',
    storageBucket: 'vivalink-5b6a0.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlMu544lu7GYByTBEHaeBe8Ld5YlaGc54',
    appId: '1:243357669534:web:e18ff7883ecf51cae8c38f',
    messagingSenderId: '243357669534',
    projectId: 'vivalink-5b6a0',
    authDomain: 'vivalink-5b6a0.firebaseapp.com',
    databaseURL: 'https://vivalink-5b6a0-default-rtdb.firebaseio.com',
    storageBucket: 'vivalink-5b6a0.firebasestorage.app',
    measurementId: 'G-5NG14JSLYM',
  );
}
